### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by flieks** [CharlesPockert/aurelia-bs-grid-demo#8]
Hi,

Sorting is not working in [demo](http://charlespockert.github.io/aurelia-bs-grid-demo/#/local)
when you sort first on id and then on name for example

Greetings

**Comment by CharlesPockert** [comment]
Hi @flieks - I need to turn off issues on this, the repo has moved to https://github.com/CharlesPockert/aurelia-bs-grid, any chance you can re-add it there?

**Comment by flieks** [comment]
yes thanks
